name: Deploy static content to Pages
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - "public/**"
      - "index.html"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "deploy-pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Build Info
        run: |
          sudo apt-get install jq
          echo "{ \"build_date\": \"$(date)\", \"commit_sha\": \"$GITHUB_SHA\" }" | jq . > public/build-info.json

      - name: Generate Index
        run: |
          if [ -d public/n ]; then
            for file in `ls public/n/*.json`; do basename -s .json $file; done | jq -R . | jq -cs . > public/n/index.json
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload public repository
          path: "./public"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
