name: Trigger Derived Repos Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger:
    if: github.repository == 'june07-aname/aname-template'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout template repo
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.PAT }}" | gh auth login --with-token

      - name: Trigger sync workflows in derived repos
        run: |
          DERIVED_REPOS=$(gh repo list june07-aname --json name --jq '.[] | select(.name | test("^aname-[a-z0-9]{2}$")) | .name')
          for REPO in $DERIVED_REPOS; do
            echo "Triggering sync in $REPO..."
            if [[ $REPO == 'aname-00' ]]; then
              gh workflow run sync-with-template-repo.yml --repo june07-aname/$REPO
            fi
          done